
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-6pm-2
owner: ucsb-cs156-s23
repo_name: team03-s23-6pm-2
pull_requests: [{"author":{"id":"U_kgDOBtKZtg","is_bot":false,"login":"jgarcia-ucsb","name":""},"headRefName":"dogFrontEnd","number":19,"title":"Added all Dog frontend CRUD + tests + storybook for pages and storiesâ€¦","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-2/pull/19"},{"author":{"id":"MDQ6VXNlcjM2NTczMjU5","is_bot":false,"login":"Jacob10383","name":"Jacob"},"headRefName":"port-restaraunt01","number":18,"title":"Bring over RESTARAUNT FRONT","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-2/pull/18"}]
